# -*- coding: utf-8 -*-
"""numbi

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WgnpaTtp7neqrs5NuzoZbhOdnTU1NOy4
"""

n=int(input())
if n>0:
  print('Positive')
if n<0:
  print('Negative')
if n==0:
  print('Zero')